spring:
  mvc:
    date-format: yyyy-MM-dd
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html; charset=utf-8
  messages:
    basename: i18n.login
  http:
    encoding:
      charset: utf-8
server:
  tomcat:
    uri-encoding: utf-8
  port: 8889

